@baseUrl = http://localhost:3000/api
@resourceName=products

# Categories

# @name getAllProducts
GET {{baseUrl}}/products
###

# @name addNewProduct
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Laptop"
}
###

# @name updateCategory
PATCH {{baseUrl}}/categories/2
Content-Type: application/json

{
  "name": "New Laptop"
}
###

# @name removeCategory
DELETE {{baseUrl}}/categories/3
Content-Type: application/json
###